### ISSUE TITLE
Possible Normalization Typo

### ISSUE THREAD

**Issue by pshea76** [MarineRoboticsGroup/dcsam#3]
Hey guys,

I think this is meant to be if(!normalized)

https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMixtureFactor.h#L68
https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMaxMixtureFactor.h#L78

Best,
Pat

**Comment by keevindoherty** [comment]
Thanks for digging into this Pat! I think this may actually just be a bit of confusing terminology - thanks for pointing this out!

This is a bit subtle: most of the "off-the-shelf" GTSAM nonlinear factors discard the normalizing constant in the negative log likelihood, so that the corresponding squared residuals appear as `r(x) = 0.5*|| h(x) - z ||^2` (where `h(x)` is a measurement model, `x` are the latent variables, `z` is a measurement, and the norm is the appropriately chosen one [e.g. the Mahalanobis distance]). This presents some issues when the normalization terms are no longer constant with respect to the optimization variables. In particular, when there is a discrete decision between factors with different noise models (e.g. null/alternative hypothesis) this normalization term can change the optimal decision.

If `normalized = true` we mean that the input component factors of the mixtures are themselves _already_ normalized. That is to say, rather than returning `r(x) = || h(x) - z||^2`, they return `r(x) = - log N + 0.5 || h(x) - z ||^2`. In the (more typical) case where these components are not themselves "normalized" (so we set `normalized = false`), we attempt to compute (internally) the appropriate normalization constant. We should definitely document this more clearly and possibly update the name of that `bool`.

**Comment by keevindoherty** [comment]
While looking into something else, @kurransingh and I realized that there is in fact a small bug in the `DCMaxMixtureFactor` implementation related to the normalization. The error lies here: https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMaxMixtureFactor.h#L88 where we determine the error for each component factor. If these errors are appropriately normalized, then this comparison is correct. In the (more common) case where these factors do not include normalization constant information in the error function, this will select the wrong factor.

**Comment by keevindoherty** [comment]
Closing for now, but general refactoring is definitely on the docket!
